spring:
  profiles:
    active: dev
  application:
    name: jenkins-collector-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: MYSQL
application:
  mq:
    concurrentConsumers: 3
    maxConcurrentConsumers: 10
server:
  port: 9090
